### ISSUE TITLE
Server side unnecessary error while disconnecting

### ISSUE THREAD

**Issue by driver1748** [ZGIT-Network/NataChat#5]
![image](https://user-images.githubusercontent.com/62016462/207872947-3c7b9cab-9a57-475e-89fb-286b9da95fe6.png)

Way to represent:
1.Connect to the server in your explorer
2.Click "disconnect" or just close the web page.

The server WILL still run, but the error outputs is annoying and unnecessary.

**Comment by Yunmoan** [comment]
我也被这个问题困扰很久了，如果您可以帮助我们修复这个问题可提交Pull Request以合并分支
我正在尝试解决此问题。
